### ISSUE TITLE
 Control plane rules

### ISSUE THREAD

**Issue by NicoleVenachi** [TrietTran1701/Packet-Reflector---P4-Utils#1]
Hi men! 
I've been learning P4 from https://github.com/p4lang/tutorials/tree/master/exercises.
In the architecture they implement, different json files (e.g., s1-runtime.json) are used to install the control plane rules in the switches.

I was wondering, in you project, which file installs the different writed rules in the switches?

Thanks a lot!

**Comment by TrietTran1701** [comment]
Hi, I'm a very new p4 learner. In my readme file, i just follow exactly the same as the following instruction [https://github.com/nsg-ethz/p4-learning/tree/master/exercises/01-Reflector](). You can reference to this link for more information

**Comment by NicoleVenachi** [comment]
I get it.

Thanks!!!!
